#!/usr/bin/env python3
"""Build the three-page iPhone Atlas from the canonical desktop artifact."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "atlas-fresh.html"
TARGET = ROOT / "atlas-mobile.html"

MOBILE_CSS = r'''
/* ============================================================
   15 — ATLAS MOBILE · three-page iPhone system
   Generated by scripts/build-atlas-mobile.py
   ============================================================ */
:root{--mobile-nav-h:calc(62px + env(safe-area-inset-bottom));}
html,body{min-height:100%;height:100%;overscroll-behavior:none;}
body{overflow:hidden;-webkit-tap-highlight-color:transparent;}
.mobile-only{display:none!important;}
.mobile-dossier-home,.mobile-brief-context,.mobile-status{display:none!important;}

@media(max-width:1080px){
  body:before{content:none!important;display:none!important;}
  .mobile-only{display:flex!important;}
  body{background:#020408;}
  .app{
    width:100%;height:100dvh;margin:0;border:0;border-radius:0;box-shadow:none;
    grid-template-rows:calc(52px + env(safe-area-inset-top)) minmax(0,1fr);
    padding-bottom:var(--mobile-nav-h);background:#020408;
  }
  .app:before,.app:after{display:none;}
  .securebar{height:calc(52px + env(safe-area-inset-top));padding:env(safe-area-inset-top) 16px 0;border-bottom-color:rgba(198,224,246,.08);}
  .brand{gap:8px}.aperture-logo{width:20px;height:20px}.aperture-logo:before{font-size:18px}
  .brand-primary{font-size:11px}.brand i{height:13px}.brand-secondary{font-size:11px}
  .sysline{gap:8px}.sysline .system-meta{display:none}.secure-pill{height:26px;padding:0 8px;font-size:10px;}
  .temporal-band,.topbar,.console-footer,.detail{display:none!important;}
  .main{display:block;grid-row:2;min-height:0;height:100%;padding:0;}
  .panel{display:none;border:0;border-radius:0;box-shadow:none;background:#020408;}

  body[data-mobile-page="map"] .map-panel{display:block;height:100%;}
  body[data-mobile-page="cases"] .list-panel{display:block;height:100%;}
  .map-panel>.panel-inner.map-shell{height:100%;border-radius:0;}
  .map-shell:before{opacity:.72}.map-shell:after{opacity:.07;background-size:52px 52px}
  svg#atlasSvg{touch-action:none;user-select:none;-webkit-user-select:none;}
  body[data-mobile-page="map"] svg#atlasSvg{width:176%;max-width:none;margin-left:-38%;}
  .map-title{left:16px;top:15px;font-size:10px;letter-spacing:.18em;color:rgba(232,238,243,.7)}
  .map-ui{top:12px;right:12px;display:grid;grid-template-columns:repeat(2,46px);gap:8px;}
  .map-ui .zoom-readout{display:none}.iconbtn{width:46px;height:46px;border-radius:13px;font-size:18px;background:rgba(3,7,12,.82);}
  .map-fullscreen{display:grid!important;}
  .legend{left:12px;right:12px;bottom:calc(106px + env(safe-area-inset-bottom));max-width:none;flex-wrap:nowrap;overflow-x:auto;gap:13px;padding:9px 11px;font-size:10px;scrollbar-width:none;}
  .legend::-webkit-scrollbar{display:none}.legend span{white-space:nowrap;}
  .map-tip{display:none;}

  /* iOS-safe selected-case reticle: WebKit can drop filtered SVG groups after viewBox zoom. */
  .selection-beacon,.selection-bracket,.selection-spark{filter:none!important;}
  .selection-reticle{opacity:1;}
  .selection-reticle-outer{stroke:rgba(240,248,255,.98);stroke-width:.18;}
  .selection-reticle-inner{stroke:rgba(95,212,242,.96);stroke-width:.16;}
  .selection-bracket{stroke-width:.21;}
  .selection-label-bg{fill:rgba(3,7,12,.96);stroke:rgba(95,212,242,.86);}

  .mobile-case-peek{
    position:fixed;z-index:28;left:12px;right:12px;bottom:calc(var(--mobile-nav-h) + 10px);
    min-height:82px;align-items:center;gap:11px;padding:12px 12px 12px 14px;border:1px solid rgba(95,212,242,.22);border-radius:15px;
    background:rgba(6,12,19,.9);backdrop-filter:blur(22px) saturate(130%);box-shadow:0 18px 46px rgba(0,0,0,.42);
  }
  body:not([data-mobile-page="map"]) .mobile-case-peek{display:none!important;}
  .peek-copy{min-width:0;flex:1}.peek-meta{font:600 10px/1.2 var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--accent)}
  .peek-title{margin-top:5px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;font-weight:600;color:#F2F5F9}
  .peek-loc{margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;color:var(--muted)}
  .peek-open{flex:0 0 auto;min-width:90px;height:46px;padding:0 12px;border:1px solid rgba(95,212,242,.3);border-radius:12px;background:rgba(95,212,242,.1);color:#ECFAFF;font:600 11px var(--sans);}

  .mobile-nav{
    position:fixed;z-index:70;left:0;right:0;bottom:0;height:var(--mobile-nav-h);align-items:flex-start;padding:6px 10px env(safe-area-inset-bottom);
    border-top:1px solid rgba(198,224,246,.1);background:rgba(3,7,12,.92);backdrop-filter:blur(24px) saturate(135%);
  }
  .mobile-nav button{height:50px;flex:1;display:grid;place-items:center;align-content:center;gap:3px;border:0;border-radius:12px;background:transparent;color:rgba(140,150,163,.8);font:600 10px var(--sans);}
  .mobile-nav button:before{content:none!important;display:none!important}
  .mobile-nav button.active{color:#EAFBFF;background:rgba(95,212,242,.09);box-shadow:inset 0 0 0 1px rgba(95,212,242,.16)}

  /* Page 2 — full stack */
  .list-panel .panel-inner{height:100%;padding:0 16px 14px;overflow:hidden;display:flex;flex-direction:column;}
  .list-panel .panel-head{flex:0 0 auto;gap:10px;margin:0 -16px 8px;padding:14px 16px 12px;border-bottom:1px solid rgba(198,224,246,.08);background:rgba(5,9,15,.94);}
  .stack-banner-row{width:100%;min-width:0;min-height:34px;gap:10px}.stack-banner-row:first-child{align-items:flex-start}
  .stack-banner-left{display:block}.panel-title{font-size:16px;letter-spacing:.06em;text-transform:none;font-family:var(--sans)}
  .count{font-size:10px;line-height:1.35}.stack-banner-row:first-child>#caseCount{padding-top:3px;color:var(--accent)}
  .stack-banner-row:nth-child(2){display:block;overflow:visible;}
  .filter-chips{width:100%;max-width:100%;min-width:0;overflow-x:auto;gap:7px;padding-bottom:2px;scrollbar-width:none}.filter-chips::-webkit-scrollbar{display:none}
  .fchip{height:42px;padding:0 13px;font-size:10px;}
  select.fchip{padding-right:28px;background-position:calc(100% - 16px) calc(50% - 1px),calc(100% - 12px) calc(50% - 1px)}
  .stack-banner-right{display:flex;min-width:0;margin-top:8px;width:100%;}.stack-return{height:42px}.case-search{min-width:0;width:100%;height:44px;border-radius:12px;padding:0 13px;font-size:14px}.case-search:focus{width:100%;}
  .case-list{flex:1;min-height:0;overflow-y:auto;padding:0 0 calc(10px + env(safe-area-inset-bottom));}
  .case-row{min-height:64px;padding:9px 6px 9px 10px;grid-template-columns:98px minmax(0,1fr) auto;gap:9px;border-radius:10px;}
  .case-row+.case-row{border-top:1px solid rgba(198,224,246,.055)}
  .case-row.active{background:rgba(95,212,242,.07);box-shadow:inset 2px 0 var(--accent)}
  .file-id .id{font-size:10px}.file-id small{font-size:10px}.file-main .t{font-size:13px;line-height:1.25}.file-main .m{font-size:10.5px;line-height:1.3;white-space:normal;display:-webkit-box;-webkit-line-clamp:1;-webkit-box-orient:vertical}
  .row-actions .pill{max-width:78px;padding:5px 7px;font-size:8px;overflow:hidden;text-overflow:ellipsis;}

  /* Page 3 — dossier as a full page */
  body[data-mobile-page="dossier"] .app{display:none;}
  body[data-mobile-page="dossier"] .mobile-nav{display:flex!important;}
  .drawer-backdrop{display:none;opacity:1;pointer-events:auto;inset:0 0 var(--mobile-nav-h);padding:0;background:#020408;backdrop-filter:none;}
  body[data-mobile-page="dossier"] .drawer-backdrop.open{display:block;}
  .case-drawer{position:relative;inset:auto;width:100%;height:100%;max-width:none;padding:0 16px 28px;border:0;border-radius:0;background:linear-gradient(180deg,#071019,#020408 32%);box-shadow:none;overflow-x:hidden;overflow-y:auto;}
  .mobile-dossier-home{position:sticky;top:0;z-index:14;width:calc(100% + 32px);height:52px;margin:0 -16px;padding:0 16px;display:flex!important;align-items:center;gap:8px;border:0;border-bottom:1px solid rgba(198,224,246,.08);background:rgba(3,7,12,.96);backdrop-filter:blur(20px);color:#F5F9FC;text-align:left}
  .mobile-dossier-home .aperture-logo{width:20px;height:20px}.mobile-dossier-home .aperture-logo:before{font-size:18px}.mobile-dossier-home .brand-primary{font:600 11px var(--sans)}.mobile-dossier-home i{width:1px;height:13px;background:rgba(198,224,246,.14)}.mobile-dossier-home .brand-secondary{font:500 11px var(--sans)}
  .drawer-header{margin:0 -16px 10px;padding:calc(13px + env(safe-area-inset-top)) 16px 13px;grid-template-columns:minmax(0,1fr) auto;background:rgba(5,10,16,.94);border-bottom:1px solid rgba(198,224,246,.08);}
  .drawer-heading .eyebrow{font-size:9px;line-height:1.35}.case-drawer .case-title{margin-top:5px;font-size:20px;line-height:1.12;letter-spacing:-.025em}.case-drawer .loc{font-size:11px;line-height:1.4;margin-top:5px;}
  .drawer-nav{align-self:start;gap:5px}.drawer-navbtn,.case-drawer .drawer-close{width:44px;height:44px;border-radius:12px}.drawer-pos{display:none}.case-drawer .drawer-close{display:none;}
  .drawer-evidence{margin:12px 0;border-radius:14px}.carousel-stage{height:clamp(300px,44vh,380px)}.carousel-media{object-fit:contain;background:#010204}.carousel-nav{width:44px;height:44px}
  .carousel-thumbs{gap:8px;padding:9px;overflow-x:auto}.carousel-thumb{min-width:88px;width:88px;height:60px;}
  .pills{margin:10px 0;gap:7px;overflow-x:auto;flex-wrap:nowrap;scrollbar-width:none}.pills .pill{flex:0 0 auto;min-height:30px;display:flex;align-items:center;}
  .drawer-tabs{position:sticky;top:calc(90px + env(safe-area-inset-top));z-index:10;margin:0 -16px 14px;padding:8px 16px;gap:6px;overflow-x:auto;background:rgba(3,7,12,.94);backdrop-filter:blur(18px);scrollbar-width:none}.drawer-tabs::-webkit-scrollbar{display:none}
  .drawer-tab{flex:0 0 auto;min-width:auto;height:42px;padding:0 13px;border-radius:10px;font-size:9.5px;}
  .drawer-panel{padding-bottom:24px}.case-intel{padding:14px}.key-fact-copy{font-size:14px;line-height:1.55}.quote-card blockquote{font-size:14px}.why-card p,.drawer-box p,.drawer-summary{font-size:14px;line-height:1.58}
  .dossier-strip{grid-template-columns:repeat(4,minmax(118px,1fr));overflow-x:auto}.strip-cell{min-width:118px;padding:11px}.strip-cell b{font-size:9px}.strip-cell span{font-size:11px}
  .drawer-grid{grid-template-columns:1fr}.drawer-box{padding:14px}.drawer-timeline-row{grid-template-columns:72px 10px 1fr;gap:10px}.drawer-timeline-row b{font-size:10px}.drawer-timeline-row strong{font-size:14px}.drawer-timeline-row span{font-size:13px}
  .drawer-source{padding:12px 0}.drawer-source-label{flex-basis:100%;font-size:13px;line-height:1.45}.file-link{min-height:44px;padding:9px 11px;font-size:12px}.file-link small{max-width:190px;}
  .lightbox-frame{width:100vw;height:100dvh;border:0;border-radius:0}.lightbox-tools{top:calc(10px + env(safe-area-inset-top));right:10px;left:10px;overflow-x:auto}.lightbox-tools button,.lightbox-tools a{height:44px;min-width:44px;background:rgba(4,8,13,.9)}.lightbox-nav{width:46px;height:58px}.lightbox-prev{left:8px}.lightbox-next{right:8px}.lightbox-status{bottom:calc(12px + env(safe-area-inset-bottom));max-width:84vw}
}

@media(max-width:1080px) and (orientation:landscape){
  body[data-mobile-page="map"] .app{grid-template-rows:0 minmax(0,1fr);padding:0;}
  body[data-mobile-page="map"] .securebar,body[data-mobile-page="map"] .mobile-nav,body[data-mobile-page="map"] .mobile-case-peek{display:none!important;}
  body[data-mobile-page="map"] .legend{left:12px;right:auto;bottom:10px;max-width:58%;}
  body[data-mobile-page="map"] .map-ui{top:10px;right:calc(10px + env(safe-area-inset-right));grid-template-columns:repeat(4,44px)}
  body[data-mobile-page="map"] .iconbtn{width:44px;height:44px}
  body[data-mobile-page="map"] .map-title{left:calc(14px + env(safe-area-inset-left));top:13px}
  body[data-mobile-page="map"] svg#atlasSvg{width:100%;margin-left:0;}
}

body.map-immersive .app{grid-template-rows:0 minmax(0,1fr)!important;padding:0!important;}
body.map-immersive .securebar,body.map-immersive .mobile-nav,body.map-immersive .mobile-case-peek{display:none!important;}
body.map-immersive .map-ui{top:calc(10px + env(safe-area-inset-top));right:calc(10px + env(safe-area-inset-right));}
body.map-immersive .legend{bottom:calc(10px + env(safe-area-inset-bottom));}

@media(max-width:380px){
  .brand-secondary{display:none}.case-row{grid-template-columns:88px minmax(0,1fr) auto}.row-actions{display:none}.carousel-stage{height:clamp(280px,42vh,330px)}.drawer-navbtn{width:42px}
}

/* Sprint 1 — premium restraint overrides */
@media(max-width:1080px){
  body[data-mobile-page="map"] .map-panel>.panel-inner.map-shell{display:block;background:#03070C}
  body[data-mobile-page="map"] svg#atlasSvg{width:188%;height:100%;max-width:none;margin-left:-44%;transform:translateY(-8px)}
  body[data-mobile-page="cases"] .main,body[data-mobile-page="cases"] .list-panel,body[data-mobile-page="cases"] .list-panel .panel-inner{width:100%;max-width:100%;min-width:0}
  .map-ui{display:flex;flex-direction:column;gap:6px}
  .legend{left:12px;right:12px;bottom:calc(94px + env(safe-area-inset-bottom));max-width:none;display:grid;grid-template-columns:repeat(3,max-content);justify-content:space-between;gap:7px 12px;padding:9px 11px;overflow:visible}
  .legend span{white-space:nowrap}
  .mobile-case-peek{min-height:70px;gap:10px;padding:9px 10px 9px 12px;border-color:rgba(95,212,242,.18);border-radius:14px}
  .peek-title{margin-top:3px;font-size:13px}.peek-loc{margin-top:2px;font-size:10px}
  .peek-open{min-width:82px;height:44px;padding:0 10px;border-color:rgba(95,212,242,.26);border-radius:11px;background:rgba(95,212,242,.08)}
  .mobile-nav svg{width:19px;height:19px;stroke:currentColor;fill:none;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}
  .list-panel .panel-head{gap:8px;margin-bottom:6px;padding:11px 16px 10px;border-bottom-color:rgba(198,224,246,.07)}
  .stack-banner-row:first-child{order:1}.stack-banner-row:nth-child(2){order:2;display:flex!important;flex-direction:column;align-items:stretch;min-width:0;overflow:hidden}
  .stack-banner-right{order:1;margin-top:0!important}.filter-chips{order:2}
  .panel-title{font-size:18px;letter-spacing:-.02em}
  .filter-chips{position:relative;display:flex!important;width:100%;max-width:100%;min-width:0;padding-right:24px;overflow-x:auto;-webkit-mask-image:linear-gradient(90deg,#000 0,#000 calc(100% - 22px),transparent)}
  .filter-chips .fchip{flex:0 0 auto;min-width:112px}
  .filter-chips #toggleInstitutional{min-width:146px}
  .stack-banner-right{margin-top:6px}
  .case-row{min-height:58px;padding:8px 6px 8px 10px;grid-template-columns:92px minmax(0,1fr);gap:9px;border-radius:9px}
  .row-actions{display:none!important}
  .drawer-header{margin-bottom:8px;padding:calc(11px + env(safe-area-inset-top)) 16px 11px;border-bottom-color:rgba(198,224,246,.07)}
  .drawer-nav{align-self:start;display:grid;grid-template-columns:44px 44px;gap:5px}
  .drawer-pos{display:block;grid-column:1/-1;grid-row:2;min-width:0;padding-top:3px;text-align:center;font-size:10px}
  .case-drawer>.pills{display:none}
  .mobile-status{display:block!important;margin:9px 0 7px;padding:9px 11px;border-top:1px solid rgba(198,224,246,.07);border-bottom:1px solid rgba(198,224,246,.07);font:600 10px/1.35 var(--mono);letter-spacing:.045em;text-transform:uppercase;color:rgba(198,205,214,.74)}
  .mobile-status b{color:#EAFBFF;font-weight:600}.mobile-status i{padding:0 6px;color:rgba(140,150,163,.45);font-style:normal}
  .drawer-tabs{top:calc(88px + env(safe-area-inset-top));display:grid!important;grid-template-columns:repeat(3,1fr);gap:5px;overflow:visible;padding:7px 16px}
  .drawer-tab{min-width:0!important;height:42px;padding:0 8px;font-size:9.5px}
  .mobile-brief-context{display:grid!important;gap:10px;margin-top:12px}
}
@media(max-width:1080px) and (orientation:landscape){
  body[data-mobile-page="map"] .map-panel>.panel-inner.map-shell{display:flex;align-items:center;justify-content:center}
  body[data-mobile-page="map"] svg#atlasSvg{width:100%;height:100%;margin-left:0;transform:none}
  body[data-mobile-page="map"] .map-ui{flex-direction:row}
  body[data-mobile-page="map"] .legend{left:12px;right:auto;bottom:10px;max-width:58%;display:flex;flex-wrap:wrap;justify-content:flex-start}
}
'''

MOBILE_HTML_PEEK = r'''<div class="mobile-case-peek mobile-only" id="mobileCasePeek" aria-live="polite">
  <div class="peek-copy"><div class="peek-meta" id="peekMeta">Select a case</div><div class="peek-title" id="peekTitle">Tap a map marker</div><div class="peek-loc" id="peekLoc">The selected file will appear here.</div></div>
  <button class="peek-open" id="peekOpen" type="button">View case →</button>
</div>'''

MOBILE_HTML_NAV = r'''<nav class="mobile-nav mobile-only" aria-label="Atlas pages">
  <button type="button" data-page="map"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6.5 9 4l6 2.5L20 4v13.5L15 20l-6-2.5L4 20Z"/><path d="M9 4v13.5M15 6.5V20"/></svg>Map</button>
  <button type="button" data-page="cases"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 6h12M8 12h12M8 18h12"/><circle cx="4" cy="6" r="1"/><circle cx="4" cy="12" r="1"/><circle cx="4" cy="18" r="1"/></svg>Cases</button>
  <button type="button" data-page="dossier"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h9l3 3v15H6Z"/><path d="M15 3v4h4M9 11h6M9 15h6"/></svg>Dossier</button>
</nav>'''

MOBILE_JS = r'''
/* Atlas Mobile three-page controller */
let mobilePage='map';
const mobilePages=new Set(['map','cases','dossier']);
function renderMobilePeek(){
  const c=cases.find(x=>x.id===state.selectedCaseId);
  const meta=document.getElementById('peekMeta'), title=document.getElementById('peekTitle'), loc=document.getElementById('peekLoc');
  if(!meta||!title||!loc) return;
  if(!c){meta.textContent='Select a case';title.textContent='Tap a map marker';loc.textContent='The selected file will appear here.';return;}
  meta.textContent=`${c.id} · ${c.date}`; title.textContent=c.title; loc.textContent=`${c.location} · ${c.agency}`;
}
function normalizeMobileDossier(){
  const drawer=document.getElementById('caseDrawer');
  if(!drawer) return;
  if(!drawer.querySelector('.mobile-dossier-home')) drawer.insertAdjacentHTML('afterbegin','<button class="mobile-dossier-home" type="button" aria-label="Reset UAP Atlas to home"><span class="aperture-logo" aria-hidden="true"></span><span class="brand-primary">Cortana</span><i></i><span class="brand-secondary">UAP Case Atlas</span></button>');
  drawer.querySelector('.mobile-dossier-home').onclick=resetAtlasHome;
  const brief=drawer.querySelector('[data-panel="brief"]');
  const official=drawer.querySelector('[data-panel="official"] .drawer-box');
  const gaps=drawer.querySelector('[data-panel="gaps"] .drawer-box');
  if(brief&&!brief.querySelector('.mobile-brief-context')){
    const context=document.createElement('div');
    context.className='mobile-brief-context';
    if(official) context.append(official.cloneNode(true));
    if(gaps) context.append(gaps.cloneNode(true));
    brief.append(context);
  }
  drawer.querySelectorAll('[data-tab="official"],[data-tab="gaps"],[data-panel="official"],[data-panel="gaps"]').forEach(el=>el.remove());
  const c=cases.find(x=>x.id===state.selectedCaseId);
  const pills=drawer.querySelector(':scope > .pills');
  if(c&&pills&&!drawer.querySelector('.mobile-status')){
    pills.insertAdjacentHTML('afterend',`<div class="mobile-status"><b>${esc(c.status)}</b><i>·</i>${esc(compactConfidence(c.confidence))}</div>`);
  }
}
function syncMobileNav(){
  document.body.dataset.mobilePage=mobilePage;
  document.querySelectorAll('.mobile-nav [data-page]').forEach(btn=>{
    const active=btn.dataset.page===mobilePage; btn.classList.toggle('active',active); btn.setAttribute('aria-current',active?'page':'false');
  });
  if(mobilePage!=='map') document.body.classList.remove('map-immersive');
}
function setMobilePage(page,{write=true}={}){
  mobilePage=mobilePages.has(page)?page:'map';
  if(mobilePage==='dossier'){
    const id=state.selectedCaseId||(visibleStackCases()[0]||cases[0]||{}).id;
    if(id) openFullCase(id);
  }else{
    document.getElementById('drawerBackdrop')?.classList.remove('open');
    urlCaseId=null;
    drawerReturnFocus=null;
  }
  syncMobileNav(); renderMobilePeek();
  if(write) updateUrl();
}
document.querySelectorAll('.mobile-nav [data-page]').forEach(btn=>btn.addEventListener('click',()=>setMobilePage(btn.dataset.page)));
document.getElementById('peekOpen')?.addEventListener('click',()=>setMobilePage('dossier'));
document.addEventListener('atlas:home-reset',()=>{mobilePage='map';syncMobileNav();renderMobilePeek();});
function focusMobileCaseFromStack(id){
  selectCase(id,true);
  setMobilePage('map');
}
caseList.addEventListener('click',e=>{
  const row=e.target.closest('.case-row'); if(!row) return;
  const id=row.dataset.id;
  e.preventDefault(); e.stopPropagation();
  focusMobileCaseFromStack(id);
},true);
caseList.addEventListener('keydown',e=>{
  if(e.key!=='Enter'&&e.key!==' ') return;
  const row=e.target.closest('.case-row'); if(!row) return;
  const id=row.dataset.id;
  e.preventDefault(); e.stopPropagation();
  focusMobileCaseFromStack(id);
},true);
const mapFullscreen=document.querySelector('[data-map-fullscreen]');
async function toggleMapImmersive(){
  const entering=!document.body.classList.contains('map-immersive');
  document.body.classList.toggle('map-immersive',entering);
  if(entering&&document.documentElement.requestFullscreen){try{await document.documentElement.requestFullscreen();}catch(_){}}
  else if(!entering&&document.fullscreenElement&&document.exitFullscreen){try{await document.exitFullscreen();}catch(_){}}
  mapFullscreen?.setAttribute('aria-label',entering?'Exit full-screen map':'Open full-screen map');
  setTimeout(()=>setView(state.view.x,state.view.y,state.view.w),80);
}
mapFullscreen?.addEventListener('click',toggleMapImmersive);
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement) document.body.classList.remove('map-immersive');});

/* Pointer-based pan + pinch for iPhone. Mouse keeps the established handlers. */
const mapPointers=new Map(); let pinchStart=null;
svg.addEventListener('pointerdown',e=>{
  if(e.pointerType==='mouse') return;
  e.preventDefault(); svg.setPointerCapture?.(e.pointerId); cancelViewAnim();
  mapPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
  if(mapPointers.size===1) state.dragStart={x:e.clientX,y:e.clientY,view:{...state.view}};
  if(mapPointers.size===2){const p=[...mapPointers.values()];pinchStart={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),view:{...state.view},center:{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}};}
},{passive:false});
svg.addEventListener('pointermove',e=>{
  if(!mapPointers.has(e.pointerId)||e.pointerType==='mouse') return;
  e.preventDefault(); mapPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
  if(mapPointers.size===2&&pinchStart){
    const p=[...mapPointers.values()],dist=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);
    const nw=clamp(pinchStart.view.w*(pinchStart.distance/Math.max(1,dist)),8,100),nh=nw*.62;
    const rect=svg.getBoundingClientRect(),rx=(pinchStart.center.x-rect.left)/rect.width,ry=(pinchStart.center.y-rect.top)/rect.height;
    const anchorX=pinchStart.view.x+rx*pinchStart.view.w,anchorY=pinchStart.view.y+ry*pinchStart.view.h;
    setView(clamp(anchorX-rx*nw,0,100-nw),clamp(anchorY-ry*nh,0,62-nh),nw); return;
  }
  if(mapPointers.size===1&&state.dragStart){
    const dx=(e.clientX-state.dragStart.x)/svg.clientWidth*state.dragStart.view.w,dy=(e.clientY-state.dragStart.y)/svg.clientHeight*state.dragStart.view.h;
    setView(clamp(state.dragStart.view.x-dx,0,100-state.dragStart.view.w),clamp(state.dragStart.view.y-dy,0,62-state.dragStart.view.h),state.dragStart.view.w);
  }
},{passive:false});
function releaseMapPointer(e){mapPointers.delete(e.pointerId);if(mapPointers.size<2)pinchStart=null;if(mapPointers.size===1){const p=[...mapPointers.values()][0];state.dragStart={x:p.x,y:p.y,view:{...state.view}};}else if(!mapPointers.size)state.dragStart=null;}
svg.addEventListener('pointerup',releaseMapPointer);svg.addEventListener('pointercancel',releaseMapPointer);

/* Fold mobile page state into the existing hash model. */
const desktopUpdateUrl=updateUrl;
updateUrl=function(){
  desktopUpdateUrl();
  const h=location.hash.replace(/^#/,''); const p=new URLSearchParams(h); p.set('page',mobilePage);
  const next='#'+p.toString(); lastWrittenHash=next; try{history.replaceState(null,'',location.pathname+location.search+next);}catch(_){location.hash=next;}
};
const originalOpenFullCase=openFullCase;
openFullCase=function(id){originalOpenFullCase(id);mobilePage='dossier';normalizeMobileDossier();syncMobileNav();renderMobilePeek();};
const originalCloseFullCase=closeFullCase;
closeFullCase=function(){if(matchMedia('(max-width:1080px)').matches){setMobilePage('cases');return;}originalCloseFullCase();};
const originalSelectCase=selectCase;
selectCase=function(id,zoom){originalSelectCase(id,zoom);renderMobilePeek();};

const initialMobileParams=new URLSearchParams(location.hash.replace(/^#\/?/,''));
mobilePage=mobilePages.has(initialMobileParams.get('page'))?initialMobileParams.get('page'):(urlCaseId?'dossier':'map');
syncMobileNav();renderMobilePeek();
if(mobilePage==='dossier'&&state.selectedCaseId){originalOpenFullCase(state.selectedCaseId);normalizeMobileDossier();}
'''

def require_replace(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"Build failed: missing {label}")
    return text.replace(old, new, 1)

html = SOURCE.read_text(encoding="utf-8")
html = html.replace("<title>UAP Atlas — Interactive Case Dossier</title>", "<title>UAP Atlas Mobile — Map, Cases, Dossier</title>", 1)
html = require_replace(html, "</style>\n</head>", f"{MOBILE_CSS}\n</style>\n</head>", "style terminator")
html = require_replace(
    html,
    '<div class="map-ui"><span class="zoom-readout" id="zoomReadout">1.0×</span><button class="iconbtn" data-zoom="in" aria-label="Zoom in">+</button><button class="iconbtn" data-zoom="out" aria-label="Zoom out">−</button><button class="iconbtn" data-zoom="reset" aria-label="Reset view">↺</button></div>',
    '<div class="map-ui"><span class="zoom-readout" id="zoomReadout">1.0×</span><button class="iconbtn" data-zoom="in" aria-label="Zoom in">+</button><button class="iconbtn" data-zoom="out" aria-label="Zoom out">−</button><button class="iconbtn" data-zoom="reset" aria-label="Reset view">↺</button><button class="iconbtn map-fullscreen mobile-only" data-map-fullscreen aria-label="Open full-screen map">⛶</button></div>',
    "map controls",
)
html = require_replace(html, "      <div class=\"legend\"><span>", f"      {MOBILE_HTML_PEEK}\n      <div class=\"legend\"><span>", "map legend")
html = require_replace(html, '<div class="drawer-backdrop" id="drawerBackdrop">', f'{MOBILE_HTML_NAV}\n<div class="drawer-backdrop" id="drawerBackdrop">', "drawer backdrop")
html = require_replace(html, "</script>\n</body>", f"{MOBILE_JS}\n</script>\n</body>", "script terminator")
TARGET.write_text(html, encoding="utf-8")
print(f"Built {TARGET} ({TARGET.stat().st_size:,} bytes)")
